/** Alphabetized list of common diagnoses for multi-select. */
export const DIAGNOSES_OPTIONS: string[] = [
  "Anxiety",
  "Back pain",
  "Cervical strain",
  "Chronic pain",
  "Concussion / TBI",
  "Depression",
  "Disc herniation",
  "Fibromyalgia",
  "Headache / Migraine",
  "Knee injury",
  "Lumbar strain",
  "Nerve damage",
  "PTSD",
  "Radiculopathy",
  "Shoulder injury",
  "Soft tissue injury",
  "Sprain / Strain",
  "Whiplash",
  "Other",
].sort((a, b) => a.localeCompare(b));
